### ISSUE TITLE
Web interface for TGE staff - Create web client

### ISSUE THREAD

**Issue by briandavidwetzel** [thegreatexchange/tge-event-client#1]
As a TGE staff member I should be able to log into a web interface for the purpose of registering tge event participants.

**Requirements**
- 1.0 - Web interface created for data entry at any Great Exchange Event (on campus, at churches or in organizations).  Web interface should be concise, clean and easy to both read and navigate.  

**Tasks**
- [x] Initialize ember app with default packages
- [x] Setup deploy scripts using lightning deploy strategy
- [x] Update API to render event client
- [x] Add landing page
